##**Breast Cancer Prediction Using ML in Python**



In [43]:
import numpy as np
import pandas as pd

In [44]:
data=pd.read_csv('/content/breast-cancer.csv')

In [45]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [46]:
data["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [47]:
data.shape

(569, 32)

In [48]:
data.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [50]:
data.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000   
mean        0.181162  ...     16.269190      25.677223       107.261213   
std         0.027414  ...      4.833242       6.146258        33.602542   
min         0.106000  ...      7.930000      12.020000        50.410000   
25%         0.161900  ...     13.010000      21.080000        84.110000   
50%         0.179200  ...     14.970000      25.410000        97.660000   
75%         0.195700  ...     18.790000      29.720000       125.400000   
max         0.304000  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 31 columns]

In [51]:
data.duplicated().sum()

0

In [52]:
#Encoding the targeted variable
#from sklearn.preprocessing import LabelEncoder
#l_e = LabelEncoder()
#data['diagnosis']=data['diagnosis'].map({"M":1,"B":0})
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['diagnosis']= label_encoder.fit_transform(data['diagnosis'])

In [53]:
data['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [54]:
#splitting the data into training and testing
x=data.drop(['diagnosis'],axis=1)
y=data['diagnosis']

In [55]:
x.shape

(569, 31)

In [56]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [57]:
x_train.shape

(455, 31)

In [58]:
x_test.shape

(114, 31)

In [59]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [60]:
x_train

array([[-0.23712699, -1.44075296, -0.43531947, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [-0.23702031,  1.97409619,  1.73302577, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-0.23712907, -1.39998202, -1.24962228, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [-0.17630431,  0.04880192, -0.55500086, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.23675669, -0.03896885,  0.10207345, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.2371006 , -0.54860557,  0.31327591, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [61]:
#taining model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [62]:
#predict
y_pred=model.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1])

In [63]:
#geting accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9736842105263158

In [64]:
#predicting using model on the basis of inputs
data_input = (-0.17478099, -0.25698012,  1.42326216, -0.32031902, -0.32851959,
       -0.56328674, -0.98390686, -0.77069479, -0.72596174, -0.69922504,
       -0.96042428, -0.68451875,  0.27222162, -0.74640146, -0.47666829,
       -0.39989692, -0.94442957, -0.55196315, -0.86571951, -0.87021209,
       -0.71566322, -0.39224142,  1.43507375, -0.47432767, -0.43045164,
       -0.11415698, -0.94573859, -0.64825719, -0.82955846, -0.73083204,
       -0.89676905) # Example data, replace with actual data
np_df=np.asarray(data_input)
prediction=model.predict(np_df.reshape(1,-1)) # Use the predict method
if prediction[0]==0:
  print("The breast cancer is benign")
else:
  print("The breast cancer is malignant")

The breast cancer is benign


In [65]:
x_test[10]

array([-0.17478099, -0.25698012,  1.42326216, -0.32031902, -0.32851959,
       -0.56328674, -0.98390686, -0.77069479, -0.72596174, -0.69922504,
       -0.96042428, -0.68451875,  0.27222162, -0.74640146, -0.47666829,
       -0.39989692, -0.94442957, -0.55196315, -0.86571951, -0.87021209,
       -0.71566322, -0.39224142,  1.43507375, -0.47432767, -0.43045164,
       -0.11415698, -0.94573859, -0.64825719, -0.82955846, -0.73083204,
       -0.89676905])

In [66]:
#predicting using model on the basis of inputs
data_input = (-0.23711093, -0.4976419 ,  0.61365274, -0.49813131, -0.53102815,
       -0.57694824, -0.17494424, -0.36215622, -0.284859  ,  0.43345165,
        0.17818232, -0.36844966,  0.55310406, -0.31671104, -0.40524636,
        0.04025752, -0.03795529, -0.18043065,  0.16478901, -0.12170969,
        0.23079329, -0.50044002,  0.81940367, -0.46922838, -0.53308833,
       -0.04910117, -0.04160193, -0.14913653,  0.09681787,  0.10617647,
        0.49035329) # Example data, replace with actual data
np_df=np.asarray(data_input)
prediction=model.predict(np_df.reshape(1,-1)) # Use the predict method
if prediction[0]==0:
  print("The breast cancer is benign")
else:
  print("The breast cancer is malignant")

The breast cancer is benign


In [67]:
x_train[10]

array([-0.23711093, -0.4976419 ,  0.61365274, -0.49813131, -0.53102815,
       -0.57694824, -0.17494424, -0.36215622, -0.284859  ,  0.43345165,
        0.17818232, -0.36844966,  0.55310406, -0.31671104, -0.40524636,
        0.04025752, -0.03795529, -0.18043065,  0.16478901, -0.12170969,
        0.23079329, -0.50044002,  0.81940367, -0.46922838, -0.53308833,
       -0.04910117, -0.04160193, -0.14913653,  0.09681787,  0.10617647,
        0.49035329])

In [68]:
#predicting using model on the basis of inputs
data_input = (-0.23694721,  0.02898271,  2.0334026 ,  0.0274851 , -0.0859606 ,
       -0.97169365,  0.00535521,  0.26961096, -0.11046955, -1.70807212,
       -0.20366745, -0.23551681,  2.07208669, -0.36407848, -0.21429334,
       -0.22337665,  0.15143154,  0.17677622, -0.28374225, -1.06866936,
       -0.08313574, -0.1009375 ,  2.47659605, -0.13807443, -0.19925456,
       -1.01626422, -0.06549697,  0.15205697, -0.49027026, -1.60905688,
       -0.33137507) # Example data, replace with actual data
np_df=np.asarray(data_input)
prediction=model.predict(np_df.reshape(1,-1)) # Use the predict method
if prediction[0]==0:
  print("The breast cancer is benign")
else:
  print("The breast cancer is malignant")

The breast cancer is malignant


In [69]:
x_test[112]

array([-0.23694721,  0.02898271,  2.0334026 ,  0.0274851 , -0.0859606 ,
       -0.97169365,  0.00535521,  0.26961096, -0.11046955, -1.70807212,
       -0.20366745, -0.23551681,  2.07208669, -0.36407848, -0.21429334,
       -0.22337665,  0.15143154,  0.17677622, -0.28374225, -1.06866936,
       -0.08313574, -0.1009375 ,  2.47659605, -0.13807443, -0.19925456,
       -1.01626422, -0.06549697,  0.15205697, -0.49027026, -1.60905688,
       -0.33137507])

##Using different value in the prediction model and getting both the results according to the data shows that prediction is working well.